version: '3.8'
services:
  web:
    build: ./Belajar_Docker
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
